WebUI/Controllers/AdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain;
using Domain.Abstract;
using Domain.Model;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class AdminController : Controller
    {
        private IRepository repository;

        public AdminController(IRepository repository)
        {
            this.repository = repository;
        }

        // GET: Admin
        public ActionResult Index(AdminFilterVeiwModel filter)
        {
            var iceCreams = repository.GetAllIceCreams();
            if (!string.IsNullOrEmpty(filter.Word))
            {
                iceCreams = iceCreams.Where(i => i.Name.Contains(filter.Word));
            }
            if (filter.Price != null)
            {
                iceCreams = iceCreams.Where(i => i.Price == filter.Price);
            }
            if (filter.Fat != null)
            {
                iceCreams = iceCreams.Where(i => i.Fat == filter.Fat);
            }
            if (filter.Hits)
            {
                iceCreams = iceCreams.Where(i => i.Hit);
            }

            return View(iceCreams.ToList());
        }

        // GET: Admin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var iceCream = repository.GetIceCream((int)id);
            if (iceCream == null)
            {
                return HttpNotFound();
            }
            return View(iceCream);
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "Id")]IceCream iceCream, HttpPostedFileBase upFile = null)
        {
            if (ModelState.IsValid)
            {
                if (upFile != null)
                {
                    Image image = new Image
                    {
                        ImageMimeType = upFile.ContentType,
                        ImageData = new byte[upFile.ContentLength]
                    };
                    upFile.InputStream.Read(image.ImageData, 0, upFile.ContentLength);
                    iceCream.Image = image;
                }

                repository.AddIceCream(iceCream);
                return RedirectToAction("Index");
            }

            return View(iceCream);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IceCream iceCream = repository.GetIceCream((int) id);
            if (iceCream == null)
            {
                return HttpNotFound();
            }
            return View(iceCream);
        }

        // POST: Admin/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IceCream iceCream, HttpPostedFileBase upFile = null)
        {
            if (ModelState.IsValid)
            {
                if (upFile != null)
                {
                    Image image = new Image
                    {
                        ImageMimeType = upFile.ContentType,
                        ImageData = new byte[upFile.ContentLength]
                    };
                    upFile.InputStream.Read(image.ImageData, 0, upFile.ContentLength);
                    iceCream.Image = image;
                }
                repository.EditIceCream(iceCream);
                return RedirectToAction("Index");
            }
            return View(iceCream);
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IceCream iceCream = repository.GetIceCream((int) id);
            if (iceCream == null)
            {
                return HttpNotFound();
            }
            return View(iceCream);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repository.DeleteIceCream(id);
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public PartialViewResult Menu()
        {
            return PartialView("_Menu");
        }

        [ChildActionOnly]
        public PartialViewResult Filter(AdminFilterVeiwModel filter)
        {
            return PartialView("_FilterCatalog");
        }
    }
}

WebUI/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Model;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CatalogController : Controller
    {
        public int ItemsCount = 12; // Параметр который устанавливает кол-во товара на странице
        private IRepository repository;

        public CatalogController(IRepository repo)
        {
            repository = repo;
        }

        // GET: Catalog
        public ViewResult Index()
        {
            // необходимо для идентификации текущей страницы сайта, в представлении ("_Menu")
            ViewBag.NamePage = "Каталог";
            return View();
        }

        #region Частичные представления для страницы Catalog

        public PartialViewResult CatalogProducts(int page = 1, FilterViewModel filter = null)
        {
            var iceCreams = repository.GetAllIceCreams().ToList();
            IFilter filterCatallog = new FilterIceCream();
            if (filter != null)
            {
                iceCreams = filterCatallog.FilterByFat(iceCreams, 0, filter.Fat);
                if (filter.Filler != null) iceCreams = filterCatallog.FilterByFillers(iceCreams, filter.Filler);
                iceCreams = filterCatallog.FilterByOderCost(iceCreams, filter.OrderSortCost);
            }

            PageInfo pageInfo = GetPageInfo(page, iceCreams);
            iceCreams = GetResultIceCream(page, pageInfo, iceCreams);

            CatalogViewModel model = new CatalogViewModel
            {
                IceCreams = iceCreams,
                filterModel = filter,
                pageInfoModel = pageInfo
            };

            return PartialView("_CatalogProducts", model);
        }

        #endregion

        #region Вспомогательные методы

        private PageInfo GetPageInfo(int page, List<IceCream> iceCreams)
        {
            PageInfo pageInfo = new PageInfo
            {
                ItemOnPage = this.ItemsCount,
                TotalPage = (int)Math.Ceiling((decimal)iceCreams.Count / this.ItemsCount),
                CarrentPage = page,
                TotalItem = iceCreams.Count
            };

            return pageInfo;
        }

        private List<IceCream> GetResultIceCream(int page, PageInfo pageInfo, List<IceCream> iceCreams)
        {
            return iceCreams.Skip((page - 1) * pageInfo.ItemOnPage).Take(pageInfo.ItemOnPage).ToList();
        }
        
        #endregion
    }
}

WebUI/Views/Shared/_AdminPanel.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Панель Администратора</title>
    @Styles.Render("~/Content/CSS/Admin")
    @Styles.Render("~/Content/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container">
        <div class="row">
            @Html.Action("Menu", "Admin")
        </div>
        <div class="row">
            @RenderBody()
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
@using Domain.Model
@using WebUI.Helpers
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/CSS")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="siteWrapper backDefault">

    <header class="pageHeader">
        <div class="container">
            <a href="@Url.Action("Index", "Home")"><img class="logoImg" src="~/Content/img/logo.svg" alt="GllacyShop" width="160" height="65"></a>
            @{
                Html.RenderPartial("_Menu");
            }

            <div class="searchBlock"></div>

            <div class="user">
                <div class="userEnter">
                    <a class="enterLink btn btnDefault btnSmall" href="@Url.Action("Login", "Account")">
                        <i class="icoEnter"></i>
                        <span class="enterTitle">Вход
                            </span>
                    </a>
                </div>
                <div class="userBasket">
                    @{
                        Html.RenderAction("UserCart", "Home");
                    }
                </div>
                <span class="userTime">C 10 до 20, ежедневно</span>
                <a class="userPhone" href="tel:88124502525">8&nbsp;812&nbsp;450-25-25</a>
            </div>

        </div>
    </header>

    <div class="mainContent">
        <div class="container">
            @RenderBody()
        </div>
    </div>

    <footer class="pageFooter">
        <div class="container">
            <div class="pageFooterSocial">
                <ul class="socialMenu">
                    <li class="socialItem">
                        <a class="linkTwitter" href="https://twitter.com"></a>
                    </li>
                    <li class="socialItem">
                        <a class="linkInstagram" href="https://www.instagram.com"></a>
                    </li>
                    <li class="socialItem">
                        <a class="linkFacebook" href="https://www.facebook.com"></a>
                    </li>
                    <li class="socialItem">
                        <a class="linkVkontakte" href="https://vk.com"></a>
                    </li>
                </ul>
            </div>
            <nav class="pageFooterNav">
                <ul class="pageFooterMenu">
                    <li class="footerMenuItem">
                        <a class="heartIco" href="@Url.Action("ForSuppliers", "Home")">Для поставщиков</a>
                    </li>
                    <li class="footerMenuItem">
                        <a href="@Url.Action("OurDocuments", "Home")">Наши документы</a>
                    </li>
                    <li class="footerMenuItem">
                        <a href="@Url.Action("AboutTehnology", "Home")">О производстве </a>
                    </li>
                    <li class="footerMenuItem">
                        <a href="@Url.Action("EcologicalyStandarts", "Home")">Экологические стандарты</a>
                    </li>
                </ul>
            </nav>
        </div>
    </footer>
</div>

@Scripts.Render("~/Content/JS")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")
@RenderSection("scripts", required: false)
</body>
</html>

WebUI/Views/Shared/_LayoutHome.cshtml
@using Domain.Model
@using WebUI.Helpers
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/CSS")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
<input class="firstBtn" type="radio" id="btn1" name="toggle" checked="">
<input class="secondBtn" type="radio" id="btn2" name="toggle">
<input class="thirdBtn" type="radio" id="btn3" name="toggle">

<div class="siteWrapper ">

    <header class="pageHeader">
        <div class="container">
            <a href="@Url.Action("Index", "Home")"><img class="logoImg" src="~/Content/img/logo.svg" alt="GllacyShop" width="160" height="65"></a>
            <nav class="pageHeaderMenu">
                <ul class="pageHeaderList">
                    <li class="item">
                        <a class="itemLink" href="@Url.Action("Index", "Catalog")">
                            Каталог
                        </a>
                    </li>
                    <li class="item">
                        <a class="itemLink" href="@Url.Action("ShippinAndPayment", "Home")">
                            Доставка и оплата
                        </a>
                    </li>
                    <li class="item">
                        <a class="itemLink" href="@Url.Action("AboutCompany", "Home")">
                            О Компании
                        </a>
                    </li>
                </ul>
            </nav>

            <div class="searchBlock"></div>

            <div class="user">
                <div class="userEnter">
                    <a class="enterLink btn btnDefault btnSmall" href="@Url.Action("Login", "Account")">
                        <i class="icoEnter"></i>
                        <span class="enterTitle">Вход
                            </span>
                    </a>
                </div>
                <div class="userBasket">
                    @{
                        Html.RenderAction("UserCart", "Home");
                    }
                </div>
                <span class="userTime">C 10 до 20, ежедневно</span>
                <a class="userPhone" href="tel:88124502525">8&nbsp;812&nbsp;450-25-25</a>
            </div>

        </div>
    </header>

    <div class="mainContent">
        <div class="container">
            @RenderBody()
        </div>
        <section class="mapBlock clearfix">
            <div class="iMap">
                <iframe height="430" frameborder="0" style="border: 0" src="https://www.google.com/maps/embed/v1/place?q=%D1%83%D0%BB.%20%D0%A1%D0%B2%D0%B5%D1%82%D0%BB%D0%B0%D0%BD%D1%81%D0%BA%D0%B0%D1%8F%2015%2C%20%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%B2%D0%BE%D1%81%D1%82%D0%BE%D0%BA%2C%20%D0%9F%D1%80%D0%B8%D0%BC%D0%BE%D1%80%D1%81%D0%BA%D0%B8%D0%B9%20%D0%BA%D1%80%D0%B0%D0%B9%2C%20%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F&key=AIzaSyBYQWWmVuAsVD8R_ZaFZ6dLvQyRO3L4c2E" allowfullscreen></iframe>
            </div>
            <div class="mapBlockContainer">
                <div class="adressBlock">
                    <div class="adressContainer">
                        <p>
                            Адрес главного офиса и<br>офлайн магазина:
                        </p>
                        <p class="adressGeneral">
                            <strong>ул. Светланская 15<br>г. Владивосток</strong>
                        </p>
                        <p class="adressPhone">
                            <span>Для заказов по телефону:</span><br>
                            <strong><a href="tel:88124502525">8&nbsp;812&nbsp;450-25-25</a></strong><br>
                            <span>(с 10 до 20 ежедневно)</span>
                        </p>
                    </div>
                    <a href="#" class="btn btnPrimary btnMedium">Форма обратной связи</a>
                </div>
            </div>
        </section>
    </div>

    <footer class="pageFooter">
        <div class="container">
            <div class="pageFooterSocial">
                <ul class="socialMenu">
                    <li class="socialItem">
                        <a class="linkTwitter" href="https://twitter.com"></a>
                    </li>
                    <li class="socialItem">
                        <a class="linkInstagram" href="https://www.instagram.com"></a>
                    </li>
                    <li class="socialItem">
                        <a class="linkFacebook" href="https://www.facebook.com"></a>
                    </li>
                    <li class="socialItem">
                        <a class="linkVkontakte" href="https://vk.com"></a>
                    </li>
                </ul>
            </div>
            <nav class="pageFooterNav">
                <ul class="pageFooterMenu">
                    <li class="footerMenuItem">
                        <a class="heartIco" href="@Url.Action("ForSuppliers", "Home")">Для поставщиков</a>
                    </li>
                    <li class="footerMenuItem">
                        <a href="@Url.Action("OurDocuments", "Home")">Наши документы</a>
                    </li>
                    <li class="footerMenuItem">
                        <a href="@Url.Action("AboutTehnology", "Home")">О производстве </a>
                    </li>
                    <li class="footerMenuItem">
                        <a href="@Url.Action("EcologicalyStandarts", "Home")">Экологические стандарты</a>
                    </li>
                </ul>
            </nav>
        </div>
    </footer>
    <div class="popupForm none">
        <form class="popupFeedbackForm" action="#" name="feedbackForm" method="post" enctype="multipart/form-data">
            <b>Мы обязательно вам ответим!</b>
            <a class="closeIco" href="#"></a>
            <input class="inputText" id="nameInput" type="text" placeholder="Как вас зовут?">
            <span class="fakePlaceholder fakeName none">Как вас зовут?</span>
            <input class="inputText" id="emailInput" type="email" placeholder="Ваша почта для ответа?">
            <span class="fakePlaceholder fakeEmail none">Ваша почта для ответа?</span>
            <textarea class="inputArea inputText" id="feedbackInput" name="feedback" cols="51" rows="7" placeholder="Напишите что-нибудь..."></textarea>
            <span class="fakePlaceholder fakeFeedBack none">Напишите что-нибудь...</span>
            <button type="submit" class="btn btnPrimary btnMedium">Отправить</button>
        </form>
    </div>
    <div class="backPopup none"></div>
</div>

@Scripts.Render("~/Content/JS")
@RenderSection("scripts", required: false)
</body>
</html>

WebUI/Views/Shared/_Menu.cshtml
<nav class="pageHeaderMenu">
    <ul class="pageHeaderList">
        <li class="item">
            <a class="itemLink @((string)ViewBag.NamePage == "Каталог"? "carrentPage":"") " href="@Url.Action("Index", "Catalog")">
                Каталог
            </a>
        </li>
        <li class="item">
            <a class="itemLink @((string)ViewBag.NamePage == "Доставка и оплата"? "carrentPage":"")" href="@Url.Action("ShippinAndPayment", "Home")">
                Доставка и оплата
            </a>
        </li>
        <li class="item">
            <a class="itemLink @((string)ViewBag.NamePage == "О Компании"? "carrentPage":"")" href="@Url.Action("AboutCompany", "Home")">
                О Компании
            </a>
        </li>
    </ul>
</nav>

WebUI/Views/Shared/_UserCart.cshtml
@using Domain.Model


<a class="btn btnDefault btnSmall" href="@Url.Action("Index", "Cart")">
    @if ((int)ViewBag.ItemInCart != 0)
    {
        <i class="ico icoFullBasket"></i>
        <span class="enterBasket">@ViewBag.ItemInCart товара</span>
    }
    else
    {
        <i class="ico icoEmptyBasket"></i>
        <span class="enterBasket">Пусто</span>
    }
</a>